-- เพิ่มชั้น Collectibles อีก 3 ชั้น (slot ไม่พอ ~61 ออเดอร์)
-- รัน: mysql -u root -p warehouse_shelf < database/seed-extra-collectibles.sql

INSERT IGNORE INTO shelves (id, category, max_levels, slot_height_cm) VALUES
('AH2', 'Collectibles', 7, 33),
('AI2', 'Collectibles', 7, 33),
('AJ2', 'Collectibles', 7, 33);

INSERT IGNORE INTO levels (shelf_id, level_num)
SELECT s.id, n.n
FROM shelves s
CROSS JOIN (
  SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7
) n
WHERE NOT EXISTS (SELECT 1 FROM levels l WHERE l.shelf_id = s.id LIMIT 1);

INSERT IGNORE INTO slots (level_id, slot_num)
SELECT l.id, n.n
FROM levels l
CROSS JOIN (
  SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
  UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
  UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
  UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
) n
WHERE NOT EXISTS (SELECT 1 FROM slots sl WHERE sl.level_id = l.id LIMIT 1);
