-- Seed data: sample shelves matching the PDF spec (optional - run after schema.sql)

INSERT IGNORE INTO shelves (id, category, max_levels, slot_height_cm, min_box_height_cm, max_box_height_cm) VALUES
('A',   'Shoes', 7, 48, 16, NULL),
('B',   'Shoes', 7, 48, 16, NULL),
('C',   'Shoes', 7, 48, NULL, 16),
('D',   'Shoes', 7, 48, NULL, 16),
('AD',  'Apparel', 7, 33, NULL, NULL),
('AE',  'Apparel', 7, 33, NULL, NULL),
('AA',  'Collectibles', 7, 33, NULL, NULL),
('AB',  'Collectibles', 7, 33, NULL, NULL),
('AC',  'Collectibles', 7, 33, NULL, NULL),
('LBA', 'Bags', 7, 50, NULL, NULL),
('LBB', 'Bags', 7, 50, NULL, NULL),
('LBC', 'Bags', 7, 50, NULL, NULL);

-- Create levels 1-7 for each shelf
INSERT IGNORE INTO levels (shelf_id, level_num)
SELECT s.id, n.n
FROM shelves s
CROSS JOIN (
  SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7
) n;

-- Create slots 1-50 for each level
INSERT IGNORE INTO slots (level_id, slot_num)
SELECT l.id, n.n
FROM levels l
CROSS JOIN (
  SELECT 1 AS n UNION SELECT 2 UNION SELECT 3 UNION SELECT 4 UNION SELECT 5 UNION SELECT 6 UNION SELECT 7 UNION SELECT 8 UNION SELECT 9 UNION SELECT 10
  UNION SELECT 11 UNION SELECT 12 UNION SELECT 13 UNION SELECT 14 UNION SELECT 15 UNION SELECT 16 UNION SELECT 17 UNION SELECT 18 UNION SELECT 19 UNION SELECT 20
  UNION SELECT 21 UNION SELECT 22 UNION SELECT 23 UNION SELECT 24 UNION SELECT 25 UNION SELECT 26 UNION SELECT 27 UNION SELECT 28 UNION SELECT 29 UNION SELECT 30
  UNION SELECT 31 UNION SELECT 32 UNION SELECT 33 UNION SELECT 34 UNION SELECT 35 UNION SELECT 36 UNION SELECT 37 UNION SELECT 38 UNION SELECT 39 UNION SELECT 40
  UNION SELECT 41 UNION SELECT 42 UNION SELECT 43 UNION SELECT 44 UNION SELECT 45 UNION SELECT 46 UNION SELECT 47 UNION SELECT 48 UNION SELECT 49 UNION SELECT 50
) n;
